// flow-typed signature: d6ddc8303fc9da84e20da79d64b04a49
// flow-typed version: <<STUB>>/@semantic-release/gitlab_v^3.1.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@semantic-release/gitlab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@semantic-release/gitlab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@semantic-release/gitlab/lib/definitions/errors' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/get-error' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/get-repo-id' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/glob-assets' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/publish' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/resolve-config' {
  declare module.exports: any;
}

declare module '@semantic-release/gitlab/lib/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@semantic-release/gitlab/index' {
  declare module.exports: $Exports<'@semantic-release/gitlab'>;
}
declare module '@semantic-release/gitlab/index.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab'>;
}
declare module '@semantic-release/gitlab/lib/definitions/errors.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/definitions/errors'>;
}
declare module '@semantic-release/gitlab/lib/get-error.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/get-error'>;
}
declare module '@semantic-release/gitlab/lib/get-repo-id.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/get-repo-id'>;
}
declare module '@semantic-release/gitlab/lib/glob-assets.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/glob-assets'>;
}
declare module '@semantic-release/gitlab/lib/publish.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/publish'>;
}
declare module '@semantic-release/gitlab/lib/resolve-config.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/resolve-config'>;
}
declare module '@semantic-release/gitlab/lib/verify.js' {
  declare module.exports: $Exports<'@semantic-release/gitlab/lib/verify'>;
}
